### ISSUE TITLE
seems not work

### ISSUE THREAD

**Issue by ghost** [Newt0n/DoubanFM2Xiami#1]
Hi, I changed the username and password and tried several times, still didn't work. The fav song amount is always 0.

**Comment by Newt0n** [comment]
豆瓣似乎改变了加心曲目页面加载曲目列表的方式，现在是 JSON 数据动态加载，导致直接 GET URL 得到的页面还没有加载曲目列表，尝试尽快修复，也欢迎 pull request :)

update: 已经修复，可以再试试看

**Comment by 0cean** [comment]
显示“豆瓣：获取电台加心曲目 0 首”,没有获取到曲目列表。

**Comment by Newt0n** [comment]
@0cean 是的，在上次修复后豆瓣又更新了...这次又多了一个参数，而且是放在高度混淆的 JS 里，跟进修复还需要点时间...

**Comment by Newt0n** [comment]
@yacco9999 @0cean 似乎修复了...还有需要的话可以再试试

**Comment by 0cean** [comment]
@Newt0n 测试发现终端运行提示虾米收藏成功，但似乎虾米网站登录自己的账号后发现没有提交收藏曲目。

**Comment by Newt0n** [comment]
@0cean Sorry...虾米添加收藏的部分也改了，没有重新测试，刚刚已尝试修复，麻烦再试试吧，感谢反馈 :+1:

**Comment by 0cean** [comment]
@Newt0n 可以了，多谢分享。
