### ISSUE TITLE
编码变了？获取加心曲目时出错

### ISSUE THREAD

**Issue by demonnico** [Newt0n/DoubanFM2Xiami#2]
Traceback (most recent call last):
  File "db2xm.py", line 221, in <module>
    db2xm.transfer()
  File "db2xm.py", line 206, in transfer
    self.getDbFavs()
  File "db2xm.py", line 95, in getDbFavs
    print u'豆瓣：开始获取电台加心曲目...'
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)

**Comment by Newt0n** [comment]
@demon1105 是的，豆瓣改版很频繁，上次多了一个参数放在混淆的 JS 里还没更进...修复估计还要点时间，欢迎 pull request :D

**Comment by demonnico** [comment]
@Newt0n 
Roger.
Thanks for reply.

**Comment by Newt0n** [comment]
@demon1105 似乎修复了...还有需要的话可以再试试

**Comment by demonnico** [comment]
It workes.
:D
@Newt0n
