### ISSUE TITLE
请问有在虾米搜索豆瓣FM当前播放歌曲的脚本么?

### ISSUE THREAD

**Issue by shinji-ikari** [Newt0n/DoubanFM2Xiami#3]
之前搜到过一个脚本↓
doubanFM2NetEase
doubanFM searching in netease cloud music

现在163崩的要命.太多歌曲不能播放.在虾米搜了搜发现有.想换去虾米.不过这脚本只能用在163.
用相似的搜了一下发现有这个添加红心的脚本.不过这东西好像不是一回事儿....想请问一下有类似的搜索脚本么?

**Comment by Newt0n** [comment]
@shinji-ikari 这个确实不是你要找的那种，你要的应该是浏览器脚本，听豆瓣FM的时候在虾米/网易查找对应的歌，我没有类似的需求所以也没有收藏这样的脚本，抱歉 😂

**Comment by xavierskip** [comment]
@shinji-ikari 我的脚本已经更新，要不要试一下？https://greasyfork.org/zh-CN/scripts/11674-doubanfm2search
